### ISSUE TITLE
process.stdout.getColorDepth is not a function

### ISSUE THREAD

**Issue by zullusa** [databoxtech/yii2-angular-template#1]
Hi!

> \app\ng serve
> \app\node_modules\@angular\cli\utilities\color.js:14
>     process.stdout.getColorDepth() > 1;
>                    ^
> 
> TypeError: process.stdout.getColorDepth is not a function
>     at Object.<anonymous> (\app\node_modules\@angular\cli\utilities\color.js:14:20)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (\app\node_modules\@angular\cli\models\analytics.js:18:17)
>     at Module._compile (module.js:652:30)

npm version = 6.13.7
nodejs version = v8.11.3

What am I doing wrong?

**Comment by zullusa** [comment]
Sorry, I have updated my node to 12.16.3 version, and It has worked.
